### ISSUE TITLE
About the name

### ISSUE THREAD

**Issue by Arnau478** [TalonFox/zorroOS#1]
I just was curious about the name you chose... I also have an OS called owl-os... You've started your project 7 days ago and I would like to know what was the inspiration for your OS name. Does it have something to do with the fact that you recently stared my project?

Also, it's impressive the amount of code you've written in only 7 days... Did you copy/steal code from somewhere or someone? Just curious. Note that if the original code has a license such as GPLv3 you have to license your code with that license too!

Really cool name, I also liked the name when I chose it. Bye 🙂

**Comment by TalonFloof** [comment]
Hello, @Arnau478 
First, The name owlOS was chosen because my previous rewrites of my operating system (which is 7 rewrites!) had the tradition of using bird names. The 6th rewrite used eagleOS as it's name for instance. The name owlOS was simply chosen because it was another bird name. I never intended to copy the name of your operating system.

Second, the source code of owlOS was not stolen, owlOS was worked on before it was put on GitHub. That's why it appears like I've made a lot of progress in 7 days.

**Comment by Arnau478** [comment]
Okay, I wasn't pretending to say you've copied the name, just curious... So did you search your OS on GitHub and found mine?

Anyway, sorry to bother you, and happy coding :smile: :+1:

**Comment by TalonFloof** [comment]
To answer your question, Yes. I did search owlOS on GitHub and found not only your operating system, but I also found [an IoT operating system named OWLOS](https://github.com/KirinDenis/owlos).

I wish you best of luck on your operating system as well.
