### ISSUE TITLE
Invalid builtin function: @enumToInt

### ISSUE THREAD

**Issue by glyh** [TalonFox/zorroOS#3]
Hello I'm using 0.11.0-dev.3898+35a8e8a06, and this function is renamed. Could you clarify which version of zig you're using. Also by the way it's better to stick to some zig version that [zvm](https://github.com/tristanisham/zvm) has provided:
```
  0.7.1
  0.6.0
  0.4.0
  0.1.1
  0.8.1
  0.10.0
  0.9.0
  0.2.0
  master
  0.5.0
  0.10.1
  0.8.0
  0.7.0
  0.3.0
  0.9.1
```

**Comment by TalonFloof** [comment]
Hi @glyh, thank you for bringing my attention to this. I was not aware that such a major change was made to the master builds, and since I didn't use a versioning system like zvm, I didn't know that this change was made. I will be shortly committing a version of zorroOS that will build with the latest master builds of Zig. Also to note, as much as I'd like to use a stable version, zorroOS relies on features exclusive to 0.11.0 so until it releases I have to use master builds.

**Comment by TalonFloof** [comment]
The commit in question has been pushed, you should now be able to use `0.11.0-dev.3898+35a8e8a06` to build zorroOS. Feel free to reopen this issue if you're having any further compilation issues :3
